---

- name: tt-RSS | PHP modules
  tags:
    - package
  package:
    name: 
      - php-cli
      - php-gd
      - php-curl
      - php-pgsql
      - php-mbstring
      - php-xml

- name: tt-RSS | git clone
  tags:
    - package
    - git
  git:
    repo: "{{ ttrss_repo }}"
    dest: "{{ ttrss_www }}"
    depth: 1
    umask: '0027'
  notify: restart tt-rss

- name: tt-RSS | set group
  tags:
    - permissions
  file:
    path: "{{ ttrss_www }}"
    group: www-data
    recurse: yes

- name: tt-RSS | writeable paths
  tags:
    - permissions
  file:
    path: "{{ ttrss_www }}/{{ item }}"
    state: directory
    mode: 'g+w'
    recurse: yes
  with_items:
    - cache
    - feed-icons
    - lock

- name: tt-RSS | config files
  tags:
  - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
  with_items:
  - { src: config.php, dest: "{{ ttrss_www }}" }
  - { src: tt-rss.service, dest: /etc/systemd/system }
  notify: restart tt-rss

- name: tt-RSS | nginx config
  include_role:
    name: nginx
    tasks_from: site.yml
  with_items: tt-rss

- name: tt-RSS | updater service
  tags:
  - service
  service:
    name: tt-rss
    state: started
    enabled: yes

- name: tt-RSS | DB user
  tags:
  - db
  become_user: postgres
  postgresql_user:
    name: "{{ ttrss_user }}"
    password: "{{ ttrss_db_pw }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: tt-RSS | DB
  tags:
  - db
  become_user: postgres
  postgresql_db:
    name: "{{ ttrss_user }}"
    owner: "{{ ttrss_user }}"

